; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:feather_rp2040_default]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board = adafruit_feather
board_build.core = earlephilhower
monitor_speed = 115200
lib_deps = 
	pololu/VL53L1X@^1.3.1
	;sparkfun/SparkFun VL53L1X 4m Laser Distance Sensor@^1.2.12
build_flags = 


[env:feather_rp2040_uros]
extends = env:feather_rp2040_default
lib_deps = 
	https://github.com/micro-ROS/micro_ros_platformio
	pololu/VL53L1X@^1.3.1
	;sparkfun/SparkFun VL53L1X 4m Laser Distance Sensor@^1.2.12
board_microros_distro = humble
board_microros_transport = serial
board_microros_user_meta = atomic.meta
build_flags = 
	-D ROS
